# ruff: noqa: E501
"""Build the small, reviewed Stage 5 seed corpus from project-original examples."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

from finpulse_llm.data.config import load_data_config

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CONFIG = PROJECT_ROOT / "configs" / "data" / "training_pipeline.toml"
DEFAULT_OUTPUT = PROJECT_ROOT / "data" / "raw" / "finpulse_seed_v1.jsonl"


@dataclass(frozen=True)
class SeedSpec:
    id: str
    category: str
    subtopics: tuple[str, ...]
    difficulty: str
    user: str
    assistant: str


def _specs() -> tuple[SeedSpec, ...]:
    return (
        SeedSpec("fp_ta_0001", "technical_analysis", ("market_structure", "multi_timeframe"), "intermediate", "A weekly chart is making higher highs and higher lows, while the four-hour chart has just formed a lower high and lower low. How should this be interpreted?", "The weekly chart describes the dominant higher-timeframe uptrend, while the four-hour structure suggests a shorter-term correction or local downtrend. Neither timeframe cancels the other; they answer different horizon questions. A careful analysis would identify whether the four-hour decline holds above a meaningful weekly swing low and whether buyers regain a broken four-hour level. A weekly close below the higher-timeframe higher low would weaken the broader bullish structure, while a four-hour higher low followed by a higher high would support the pullback interpretation. Until one of those confirmations occurs, the evidence is mixed rather than directionally certain."),
        SeedSpec("fp_ta_0002", "technical_analysis", ("rsi", "trend"), "beginner", "RSI is below 30 during a persistent downtrend. Explain why this does not automatically create a buy signal.", "RSI below 30 shows that recent losses have been large relative to recent gains; it does not establish that selling pressure has ended. In a strong downtrend, RSI can remain oversold while price continues to make lower lows. A mean-reversion bounce is possible, but useful confirmation could include a break of bearish structure, improving volume on advances, a bullish divergence, or a reclaim of support. The bullish idea is invalidated if price continues closing below the relevant swing low or support zone. RSI should therefore change the probability assessment, not produce certainty by itself."),
        SeedSpec("fp_ta_0003", "technical_analysis", ("breakout", "volume"), "intermediate", "What evidence makes an upside breakout more credible, and what would invalidate it?", "A more credible breakout usually closes above a well-defined resistance area rather than merely wicking through it. Expanding volume, broader market participation, and follow-through during subsequent candles strengthen the case that demand absorbed available supply. A retest that holds the former resistance as support can add confirmation. None of these features guarantees continuation. The setup weakens if price quickly returns to the prior range, follow-through volume disappears, or the retest closes decisively below the breakout area. Invalidation should be tied to that structure rather than an arbitrary percentage move."),
        SeedSpec("fp_ta_0004", "technical_analysis", ("atr", "stop_loss"), "intermediate", "How can ATR inform stop placement without predicting market direction?", "ATR estimates the typical price range over a chosen lookback, so it helps distinguish ordinary noise from an unusually large move. A stop placed far inside normal ATR-sized movement may be triggered even when the trade thesis remains intact. ATR can therefore help scale a structural stop or compare volatility across assets. It does not identify bullish or bearish direction, and an ATR multiple should not replace a valid invalidation level. Position size must be reduced when a volatility-aware stop is wider so that account risk stays constant. Gaps and sudden volatility expansion can still cause losses beyond the planned stop."),
        SeedSpec("fp_ta_0005", "technical_analysis", ("divergence", "momentum"), "intermediate", "Price makes a new low but MACD histogram makes a higher low. What does that divergence mean and what does it not mean?", "The higher MACD-histogram low suggests bearish momentum is decelerating even though price has made a lower low. That can precede stabilization or reversal, but it is only a warning that the existing move may be losing force. It does not prove buyers have taken control or establish a precise entry. Confirmation could come from a higher price low, a break above a lower high, or stronger volume on advances. The constructive interpretation fails if momentum expands negatively again and price continues accepting below the new low."),
        SeedSpec("fp_ta_0006", "technical_analysis", ("liquidity_sweep", "support"), "advanced", "Explain a downside liquidity sweep followed by an immediate reclaim, including the bearish alternative.", "A move below clustered prior lows can trigger resting stops and attract breakout shorts. If price rapidly reclaims the level, the move may represent a liquidity sweep: forced selling was absorbed and sellers could not maintain acceptance below support. The bullish case becomes stronger with follow-through, rising spot volume, and a higher low above the reclaimed area. The bearish alternative is that the reclaim is temporary and simply retests broken support from below. A renewed close beneath the swept lows, especially with expanding volume, invalidates the bullish interpretation."),
        SeedSpec("fp_ta_0007", "technical_analysis", ("support", "resistance"), "beginner", "Why should support and resistance usually be treated as zones rather than exact prices?", "Orders are distributed across different prices, venues, and participants, so reactions rarely occur at one mathematically exact level. Prior closes, wicks, high-volume areas, and psychological prices can cluster into a region where supply or demand becomes more likely. Treating the area as a zone reduces false precision and encourages analysis of how price behaves inside it. A zone is still not guaranteed to hold. Repeated tests can consume available orders, and acceptance beyond the far side of the zone may signal that the original support or resistance thesis is invalid."),
        SeedSpec("fp_ta_0008", "technical_analysis", ("ema", "sma"), "beginner", "Compare an EMA with an SMA and explain why neither is a forecast.", "An SMA assigns equal weight to every observation in its lookback, while an EMA gives greater weight to recent prices and therefore reacts faster to new movement. The faster response can be useful for detecting short-term change, but it can also produce more whipsaws. Both indicators summarize historical prices; neither knows future order flow, news, or liquidity. Their slopes, crossovers, and relationship to price can describe trend context, but a trading thesis still needs structure, risk limits, and confirmation. A moving-average signal should be treated as evidence, not a guaranteed forecast."),
        SeedSpec("fp_ta_0009", "technical_analysis", ("macd", "momentum"), "intermediate", "MACD crosses bullishly while both lines remain below zero. Give a careful interpretation.", "A bullish MACD crossover below zero suggests short-term momentum has improved relative to the preceding decline. Because both lines remain below the zero line, the broader momentum regime may still be bearish, so the crossover can represent a countertrend rebound rather than a confirmed reversal. Context from price structure, volume, and higher timeframes matters. A break above a prior lower high would strengthen the reversal case. If price makes another lower low and MACD turns down again, the constructive interpretation is invalidated."),
        SeedSpec("fp_ta_0010", "technical_analysis", ("fakeout", "consolidation"), "advanced", "Price briefly breaks above a month-long range and then closes back inside. How should fakeout risk be assessed?", "Returning inside the range shows that buyers failed to maintain acceptance above resistance, which raises fakeout risk. The assessment should examine breakout volume, how quickly price returned, whether leveraged positioning became crowded, and whether the former range high is reclaimed on a closing basis. A failed retest from below would favor a move back through the range, while a rapid reclaim with renewed demand could rescue the breakout. The range boundaries define useful invalidation references. One close alone changes the evidence, but it does not make the next direction certain."),
        SeedSpec("fp_cd_0001", "crypto_derivatives", ("funding", "open_interest"), "intermediate", "Crypto price rises while funding becomes strongly positive and open interest expands. Explain both the continuation case and the risk.", "Rising price with expanding open interest shows that new derivative exposure is entering, while strongly positive funding indicates longs are paying shorts. The continuation case is that demand is strong enough to absorb the funding cost and new longs are supporting trend expansion. The risk is that positioning becomes crowded and highly leveraged, creating fuel for a long-liquidation cascade if price loses support. Spot volume, basis across maturities, and the distribution of open interest across venues help distinguish durable demand from leverage-led speculation. The signals are informative but not independently predictive."),
        SeedSpec("fp_cd_0002", "crypto_derivatives", ("futures_basis", "annualization"), "advanced", "What does a positive futures basis represent, and why can a large annualized basis be misleading?", "A positive basis means the futures price trades above spot, often reflecting financing costs, demand for leveraged long exposure, and the time remaining until expiry. Annualizing a short-dated basis makes contracts easier to compare, but it assumes the observed spread persists at the same rate. That assumption can fail when basis compresses, liquidity changes, or the position cannot be rolled at similar terms. Fees, margin requirements, execution costs, and exchange risk also reduce realizable returns. Basis is therefore a market-pricing signal and potential relative-value input, not a guaranteed yield."),
        SeedSpec("fp_cd_0003", "crypto_derivatives", ("liquidations", "market_microstructure"), "intermediate", "Why can liquidation data explain acceleration without proving what originally caused a crypto move?", "Liquidations are forced position closures triggered after price has already moved far enough to breach margin requirements. Those market orders can deepen the move, trigger additional liquidations, and create a feedback loop, so they help explain acceleration. They do not establish the initial catalyst, which could be spot selling, news, a large order, or broader risk repricing. The data can also be incomplete across venues. A careful analysis separates the initiating flow from the forced-flow cascade and looks for spot activity, timing, and post-liquidation structure before inferring a durable direction."),
        SeedSpec("fp_cd_0004", "crypto_derivatives", ("spot_vs_derivatives", "volume"), "intermediate", "Why might a spot-led crypto rally be viewed differently from a perpetual-led rally?", "A spot-led rally reflects purchases of the underlying asset without requiring the same liquidation-sensitive leverage as perpetual futures. It may therefore represent more durable demand, especially when spot volume and broad participation expand. A perpetual-led rally can still continue, but rising open interest and funding may make it more dependent on leveraged positioning and vulnerable to forced unwinds. The distinction is probabilistic, not absolute: spot buyers can reverse, and derivatives can hedge real exposure. Comparing venue-level volume, basis, funding, and open interest provides a fuller picture."),
        SeedSpec("fp_cd_0005", "crypto_derivatives", ("btc_dominance", "relative_strength"), "beginner", "How should falling BTC dominance be interpreted when the total crypto market is expanding?", "Falling BTC dominance during an expanding total market often means altcoins are gaining market capitalization faster than Bitcoin, which can indicate broader risk appetite or capital rotation. It does not mean Bitcoin must be falling, and it does not guarantee every altcoin will outperform. Stablecoin supply changes, new token issuance, and a small number of large assets can affect the measure. Confirmation can come from altcoin breadth, relative-strength pairs, and spot volume. A reversal in those measures or a sharp liquidity contraction would weaken the rotation thesis."),
        SeedSpec("fp_cd_0006", "crypto_derivatives", ("leverage", "liquidation"), "beginner", "Explain why leverage changes liquidation risk even if the market thesis is correct over a longer horizon.", "Leverage reduces the adverse price movement the position can tolerate before margin is exhausted. A trader can therefore be liquidated by ordinary short-term volatility even if the longer-horizon thesis later proves correct. Funding costs, maintenance-margin changes, and slippage can narrow the buffer further. Risk should be framed around liquidation distance, structural invalidation, and account-level loss rather than expected direction alone. Lower leverage, smaller size, and additional collateral can create more room, but none removes gap or exchange risk."),
        SeedSpec("fp_cd_0007", "crypto_derivatives", ("correlation", "regime"), "intermediate", "Why should crypto-equity correlation be treated as regime-dependent?", "Correlation summarizes how assets moved over a selected historical window; it is not a permanent economic constant. Crypto and equities may move together when global liquidity, real yields, or broad risk appetite dominate, then decouple when crypto-specific regulation, protocol events, or positioning becomes more important. The measured value also changes with timeframe and sampling frequency. Portfolio analysis should test multiple windows and stress scenarios rather than extrapolate one recent coefficient. A correlation breakdown is evidence that the regime may be changing, not proof of a new stable relationship."),
        SeedSpec("fp_cd_0008", "crypto_derivatives", ("open_interest", "positioning"), "advanced", "Open interest reaches a record while price stays in a narrow range. What can and cannot be inferred?", "Record open interest shows that a large amount of derivative exposure remains open, but every contract has both a long and a short, so the number is not directionally bullish or bearish by itself. The narrow range may reflect balanced conviction, hedging, basis trades, or growing leverage before a breakout. Funding, options skew, spot flow, and venue concentration help characterize positioning. Elevated leverage can increase volatility once the range breaks, but the direction and durability still require confirmation from actual price acceptance and underlying demand."),
        SeedSpec("fp_sf_0001", "stock_fundamentals", ("revenue", "margins"), "intermediate", "Revenue grows quickly while operating margin contracts. How should an analyst assess the quality of growth?", "Fast revenue growth is constructive only if the economics of obtaining that growth are sustainable. Contracting operating margin may reflect temporary investment in distribution or product development, but it can also signal weaker pricing, unfavorable mix, or costs rising faster than sales. The analyst should compare gross margin, customer acquisition costs, operating expenses, retention, and management's path to scale. Cash-flow conversion adds another quality check. The evidence is mixed until the margin pressure is explained; revenue growth alone does not establish improving intrinsic value."),
        SeedSpec("fp_sf_0002", "stock_fundamentals", ("eps", "share_count"), "intermediate", "EPS rises even though operating income is flat. List mechanisms that could explain the difference and how to evaluate them.", "EPS can rise with flat operating income if the company repurchases shares, pays less interest, benefits from a lower tax rate, or records non-operating gains. These mechanisms differ in repeatability. A falling share count can improve per-share economics, but value creation depends on the repurchase price and balance-sheet cost. Tax benefits and one-time gains may not persist. Compare diluted share count, operating income, interest expense, taxes, and adjusted versus reported earnings. The key question is whether underlying operating cash generation improved, not merely whether the headline EPS increased."),
        SeedSpec("fp_sf_0003", "stock_fundamentals", ("free_cash_flow", "working_capital"), "intermediate", "A profitable company reports negative free cash flow for two years. What should be investigated?", "Net income is accrual-based, while free cash flow reflects actual operating cash after capital expenditure. Persistent negative free cash flow may result from heavy growth investment, rising inventory or receivables, weak collections, restructuring payments, or poor earnings quality. Investigate operating cash flow before capex, maintenance versus expansion investment, working-capital trends, stock-based compensation, and whether spending is generating future returns. Negative free cash flow is not automatically bad for an early growth business, but the funding requirement and path to self-financing must be credible."),
        SeedSpec("fp_sf_0004", "stock_fundamentals", ("valuation", "pe_ratio"), "advanced", "Why can a low P/E ratio be a value opportunity or a value trap?", "A low P/E can indicate that the market underestimates durable earnings, creating an opportunity. It can also reflect earnings near a cyclical peak, deteriorating competitive position, excessive leverage, accounting gains, or an expected decline that makes the denominator unsustainable. Compare normalized earnings, cash conversion, balance-sheet risk, reinvestment needs, and valuation against realistic scenarios rather than one trailing number. A catalyst is not required for value to exist, but evidence that fundamentals are stabilizing reduces trap risk. The multiple alone cannot distinguish cheapness from justified pessimism."),
        SeedSpec("fp_sf_0005", "stock_fundamentals", ("balance_sheet", "net_debt"), "beginner", "Explain why falling debt does not necessarily mean a company's balance sheet improved.", "Debt reduction is positive in isolation, but the funding source matters. If a company uses nearly all of its cash, sells productive assets, or issues heavily dilutive equity, liquidity and per-share value may worsen even as gross debt falls. Analysts should examine net debt, maturity timing, interest coverage, covenant headroom, and ongoing free cash flow. The business may also need cash for working capital or investment. Balance-sheet improvement therefore means stronger resilience and financing capacity, not simply a smaller debt line."),
        SeedSpec("fp_sf_0006", "stock_fundamentals", ("earnings", "guidance"), "intermediate", "A company beats the quarter but lowers full-year guidance. Explain the conflicting signals.", "The quarterly beat shows that recent results exceeded the reference expectation, but lower full-year guidance indicates management now expects weaker future performance or greater uncertainty. The beat may have come from timing, cost cuts, tax effects, or conservative estimates rather than durable demand. Review the guidance components, backlog, margins, cash flow, and whether the reduction is company-specific or macro-driven. Markets often focus more on the changed forward path than the historical beat. The combined evidence is mixed and should not be reduced to a single bullish or bearish label."),
        SeedSpec("fp_ma_0001", "macroeconomics", ("cpi", "monetary_policy"), "intermediate", "Headline inflation falls but services inflation and wage growth remain firm. What tension does this create for monetary policy?", "Lower headline inflation suggests disinflation is progressing, possibly because goods or energy pressures are easing. Firm services inflation and wages can indicate persistent domestic cost pressure, making policymakers cautious about declaring victory. The central bank must balance the risk of keeping policy restrictive for too long against the risk of easing before underlying inflation is controlled. Monthly composition, labor productivity, inflation expectations, and several consecutive readings matter more than one release. The evidence supports a mixed policy outlook rather than an automatic rate cut."),
        SeedSpec("fp_ma_0002", "macroeconomics", ("bond_yields", "dxy"), "advanced", "Bond yields and DXY rise together. Describe possible implications for global risk assets.", "Higher yields can raise discount rates and borrowing costs, while a stronger dollar can tighten global funding conditions and pressure dollar-denominated borrowers. Together they may be a headwind for long-duration equities, emerging markets, and commodities. The cause matters: yields rising on stronger real growth can support earnings expectations, whereas a rise driven by inflation or tighter policy may be less favorable. Currency hedging, regional exposure, and starting valuation also affect outcomes. The combination shifts probabilities but does not guarantee a uniform decline across risk assets."),
        SeedSpec("fp_ma_0003", "macroeconomics", ("unemployment", "labor_force"), "beginner", "How can unemployment rise during a month when payroll employment also increases?", "The measures come from different surveys and capture different concepts. Unemployment can rise if the labor force expands faster than employment, for example when previously inactive people begin searching for work. Payrolls can still increase because employers added jobs, while the household survey records a larger increase in job seekers. Revisions, multiple jobholders, and sampling noise can widen short-term differences. A balanced assessment considers participation, employment-population ratios, hours worked, wages, and multi-month trends rather than treating either headline as complete by itself."),
        SeedSpec("fp_ma_0004", "macroeconomics", ("gdp", "inventories"), "intermediate", "Why can one quarter of negative GDP overstate weakness in underlying demand?", "GDP includes volatile components such as inventories, net exports, and government spending. A large inventory drawdown or temporary trade movement can make the headline contract even while household consumption and business final sales remain positive. Conversely, inventory accumulation can temporarily flatter growth. Examine real final sales, domestic private demand, income measures, and revisions to understand the underlying pace. One quarter is evidence of slowing output, but it is not by itself a complete recession diagnosis or a reliable forecast of the next quarter."),
        SeedSpec("fp_ma_0005", "macroeconomics", ("liquidity", "transmission"), "advanced", "Central-bank liquidity expands while policy rates remain restrictive. Explain why the asset-price effect is uncertain.", "Balance-sheet liquidity can support reserves and market functioning, while high policy rates continue to raise financing costs and discount rates. The net effect depends on who receives the liquidity, bank lending standards, collateral demand, fiscal flows, and whether reserves translate into broader credit creation. Markets may respond positively to improved liquidity even while the real economy remains constrained. The channels can also operate with different lags. Analysts should track financial conditions and transmission rather than assume balance-sheet expansion automatically overrides restrictive rates."),
        SeedSpec("fp_ma_0006", "macroeconomics", ("risk_on", "risk_off"), "beginner", "Define risk-on and risk-off behavior without treating them as permanent market states.", "Risk-on describes periods when investors are more willing to hold assets with greater economic, credit, or volatility exposure, often favoring equities, high-yield credit, and some cryptocurrencies. Risk-off describes preference for liquidity, quality, or defensive assets when uncertainty rises. These labels summarize relative behavior; they do not mean every asset in a group moves together. Regimes can change quickly with growth, inflation, policy, or positioning. Cross-asset confirmation and a stated timeframe are necessary before using the labels in analysis."),
        SeedSpec("fp_rm_0001", "risk_management", ("position_sizing", "calculation"), "beginner", "An account is $30,000. The trader risks 0.5%, enters at $75, and places a structural stop at $70. Show the position-size calculation and limitations.", "The dollar risk budget is $30,000 × 0.005 = $150. Risk per share is $75 − $70 = $5, so the maximum size before costs is $150 ÷ $5 = 30 whole shares. This calculation assumes execution at the stop price. Gaps, slippage, fees, and correlated portfolio exposure can make realized loss larger. The stop should represent thesis invalidation rather than being moved to force a preferred size. If 30 shares are not liquid enough to exit safely, the position should be reduced or skipped."),
        SeedSpec("fp_rm_0002", "risk_management", ("drawdown", "recovery"), "intermediate", "Why does drawdown recovery become harder as the loss grows?", "Losses reduce the capital base on which the recovery gain is earned. A 10% loss requires about 11.1% to recover, while a 50% loss requires 100%, because the remaining capital is only half the starting amount. This asymmetry makes avoiding ruin more important than maximizing any single trade. Drawdown controls can include smaller position sizes, exposure caps, strategy diversification, and predefined de-risking rules. They do not prevent all losses, but they preserve the ability to continue operating and reduce the behavioral pressure to chase recovery."),
        SeedSpec("fp_rm_0003", "risk_management", ("portfolio_risk", "correlation"), "advanced", "Five positions each risk 1%, but all depend on the same technology-growth factor. Why is total risk not simply diversified?", "Different tickers do not guarantee independent risk. If all five positions respond to the same rates, growth, or liquidity factor, their losses may occur together precisely when protection is needed. The nominal sum is 5%, and gaps or correlation spikes can make realized portfolio loss larger. Evaluate common drivers, beta, scenario exposure, and stress correlations rather than counting positions. Risk can be reduced through smaller aggregate exposure, genuinely different return drivers, hedges, or cash. Recent low correlation should not be assumed to persist during stress."),
        SeedSpec("fp_rm_0004", "risk_management", ("leverage", "liquidation"), "intermediate", "A crypto position's liquidation level is very close to the technical invalidation level. What risk does this create?", "If liquidation is reached before or near the planned invalidation, the exchange may forcibly close the position during fast, illiquid conditions. The trader loses control of execution and may pay additional fees or slippage even though the analytical stop was sensible. Small mark-price differences can also matter. A safer structure uses less leverage, smaller size, or more collateral so the liquidation buffer sits well beyond ordinary volatility and the intended stop. The objective is not to predict the move more confidently; it is to ensure risk mechanics do not override the trading plan."),
        SeedSpec("fp_sa_0001", "scenario_analysis", ("technical", "derivatives"), "advanced", "Price reclaims resistance while spot volume rises, but funding is already very positive. Build bullish and bearish scenarios.", "Bullish scenario: the reclaim holds, spot demand continues, and price forms higher lows above former resistance. Spot-led participation could absorb the cost of crowded perpetual longs and extend the trend. Bearish scenario: positive funding reflects excessive long leverage, spot demand fades, and price falls back into the prior range, triggering liquidations. Useful discriminators include spot-versus-perpetual volume, open-interest changes, and whether the retest holds on closing prices. A decisive loss of the reclaimed level invalidates the immediate bullish setup; sustained acceptance above it weakens the fakeout case."),
        SeedSpec("fp_sa_0002", "scenario_analysis", ("earnings", "valuation"), "advanced", "A software company accelerates revenue growth and raises guidance, but its free cash flow falls and valuation is historically high. Analyze competing cases.", "Constructive case: the company is investing ahead of durable demand, raised guidance supports the revenue acceleration, and cash flow may recover as growth spending scales. Cautious case: weaker cash conversion signals poor earnings quality or rising acquisition costs, while the high valuation leaves little room for execution mistakes. Investigate deferred revenue, retention, stock-based compensation, working capital, and the expected timing of cash-flow improvement. The evidence does not justify an automatic trade. Failure to deliver the guided growth or further deterioration in unit economics would undermine the constructive case."),
        SeedSpec("fp_sa_0003", "scenario_analysis", ("macro", "cross_asset"), "advanced", "Inflation surprises lower, equities rally, but long-term real yields continue rising. Explain continuation and reversal scenarios.", "Continuation scenario: lower inflation improves the probability of less restrictive policy, earnings expectations remain resilient, and equities absorb the higher real discount rate. Reversal scenario: real yields keep tightening financial conditions, valuation compression outweighs disinflation relief, and the initial rally proves positioning-driven. Confirmation should come from subsequent inflation data, credit spreads, earnings revisions, and market breadth. A single release is insufficient to establish a regime change. The analysis should remain conditional because the growth reason behind rising real yields can alter the outcome."),
        SeedSpec("fp_sa_0004", "scenario_analysis", ("fundamentals", "technical"), "intermediate", "A stock's fundamentals improve, but price remains below a falling 200-day average. How can both signals be incorporated?", "Improving fundamentals may support a longer-term revaluation if earnings, cash flow, and balance-sheet quality continue to strengthen. Price below a falling 200-day average shows that the market has not yet confirmed that view and that supply or skepticism remains dominant. One scenario is that price bases and eventually breaks the long-term downtrend as estimates rise. Another is that the improvements are already expected or prove temporary. Track estimate revisions, relative strength, volume, and a sequence of higher lows. Fundamental improvement changes intrinsic-value evidence; technical confirmation changes timing evidence."),
        SeedSpec("fp_tm_0001", "terminology_misc", ("live_data", "hallucination_resistance"), "beginner", "What is Bitcoin's latest exact funding rate right now?", "I do not have access to live exchange data, so I cannot provide or verify the latest Bitcoin funding rate. Funding also differs by exchange and contract, so a timestamp and venue are necessary even when data is available. If you provide those values, I can interpret whether funding is positive or negative, compare it with open interest and spot activity, and discuss what the positioning may imply. Without supplied data, inventing an exact percentage would be misleading."),
        SeedSpec("fp_tm_0002", "terminology_misc", ("probability", "uncertainty"), "beginner", "Explain the difference between saying a market outcome is possible, probable, and certain.", "Possible means the outcome can occur and has not been ruled out; it says little about likelihood. Probable means the available evidence supports a likelihood greater than competing outcomes, although the estimate may still be uncertain. Certain means no meaningful alternative remains, a standard that market analysis almost never meets because future information and behavior can change. Good analysis identifies evidence, competing scenarios, and invalidation, then uses calibrated language such as may, could, or more likely. Confidence should rise or fall as evidence changes rather than becoming an absolute prediction."),
    )


def build_records(config_path: Path = DEFAULT_CONFIG) -> list[dict]:
    config = load_data_config(config_path)
    records = []
    for spec in _specs():
        records.append(
            {
                "id": spec.id,
                "messages": [
                    {"role": "system", "content": config.system_prompt},
                    {"role": "user", "content": spec.user},
                    {"role": "assistant", "content": spec.assistant},
                ],
                "metadata": {
                    "category": spec.category,
                    "subtopics": list(spec.subtopics),
                    "difficulty": spec.difficulty,
                    "source": {
                        "type": "original",
                        "reference": "finpulse-llm-stage5-seed",
                        "license": "project-original",
                    },
                    "review": {"status": "reviewed", "reviewer": "project-author"},
                },
            }
        )
    return records


def _serialize(records: list[dict]) -> str:
    return "".join(json.dumps(item, ensure_ascii=False) + "\n" for item in records)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--write", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    text = _serialize(build_records(args.config))
    if not args.write:
        if args.output.read_text(encoding="utf-8") != text:
            raise SystemExit("Seed JSONL differs from its reviewed builder source")
        print("Verified reviewed Stage 5 seed corpus: 40 examples")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(f"Wrote 40 reviewed examples to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
